// A contact sheet using the actual PNGs at portrait size and unscaled gameplay size.
import {createServer} from '../server.mjs';
import {chromium} from '../../../local/mariokart/node_modules/playwright-core/index.mjs';
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,base=origin+'/games/pac-chad/';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
try{
  const context=await browser.newContext({viewport:{width:1200,height:710},deviceScaleFactor:1});
  const cast=[['chad','PAC-CHAD','Square jaw / black beard'],['rook','ROOK','Full cheeks / broad jaw / goatee'],['hex','HEX','Fuller cheeks / light stubble'],['ivy','IVY','Soft features / light acne'],['riot','RIOT','Feminine / rainbow hair']];
  await context.route('**/art-review',route=>route.fulfill({contentType:'text/html; charset=utf-8',body:`<!doctype html><html><head><style>*{box-sizing:border-box}body{margin:0;padding:42px;background:#10110e;color:#fff1d0;font-family:Arial}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:30px}h1{font:56px Impact;margin:0}h1 span{color:#bfff67}small{font:11px monospace;letter-spacing:1.4px;color:#b0b999}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:15px}article{border:1px solid #465039;background:#171e12;padding:17px;text-align:center}article img{width:100%;height:180px;object-fit:contain}h2{font:27px Impact;margin:16px 0 8px}p{font:10px monospace;color:#a7b395;line-height:1.7}.small{border-top:1px solid #465039;margin-top:28px;padding-top:24px}.small .grid{margin-top:20px;background:#0c1020;border:1px solid #354b95;padding:20px}.small .grid div{display:grid;place-items:center}.small img{height:51px;width:51px;object-fit:contain}.foot{margin-top:22px;display:flex;justify-content:space-between;font:10px monospace;color:#a1ad8d}</style></head><body><header><div><small>GAMESLOP / CHARACTER ART</small><h1>PAC<span>-CHAD</span></h1></div><small>FIVE FACES. NO MISTAKING THEM.</small></header><section class="grid">${cast.map(([id,name,detail])=>`<article><img src="${base}assets/${id}.png"><h2>${name}</h2><p>${detail}</p></article>`).join('')}</section><section class="small"><small>GAMEPLAY SIZE / 51 PX / ORIGINAL ART AT 1×</small><div class="grid">${cast.map(([id])=>`<div><img src="${base}assets/${id}.png"></div>`).join('')}</div></section><div class="foot"><span>MATTE GRAYSCALE HERO. DISTINCT HAIR SILHOUETTES. OVERSIZED ACCESSORIES.</span><span>FIRST PLAYABLE BUILD</span></div></body></html>`}));
  const page=await context.newPage();await page.goto(origin+'/art-review');await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth));
  const alpha=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=1;const ctx=c.getContext('2d');return [...document.querySelectorAll('article img')].map(i=>{ctx.clearRect(0,0,1,1);ctx.drawImage(i,0,0);return {name:i.src.split('/').pop(),cornerAlpha:ctx.getImageData(0,0,1,1).data[3]};});});
  if(alpha.some(a=>a.cornerAlpha!==0))throw new Error('Artwork does not have transparent corners');
  await page.screenshot({path:new URL('../art/cast-preview.png',import.meta.url).pathname.replace(/^\/(\w:)/,'$1')});console.log(JSON.stringify(alpha));
}finally{await browser.close();await new Promise(r=>server.close(r));}
