'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
module.exports = async (cdp, evaluate, sleep) => {
  const guideWeaponTypes=['S','M','G','L','H','F','W','T','I','A','B','R','C','N'];
  await evaluate("window.addEventListener('error', e => (window.__qaErrors ||= []).push(e.message)); window.addEventListener('unhandledrejection',e => (window.__qaErrors ||= []).push(String(e.reason))); ");
  const check=async(expr,label)=>{assert.ok(await evaluate(expr),label);console.log('PASS '+label);};
  const screenshot=async(name)=>{const result=await cdp('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.resolve('docs/game-screenshots/commando-'+name+'.png'),Buffer.from(result.data,'base64'));};
  const click=async(selector)=>{const p=await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.scrollIntoView({block:'nearest'});const b=el.getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};})()`);await cdp('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});await sleep(35);};
  await check("document.body.dataset.ready==='1'",'page ready');
  await check("window.__gameslop.renderer.mascot.ready",'mascot sprite atlas loaded');
  await check("window.__gameslop.renderer.environment.ready",'illustrated environment atlas loaded');
  await check(`(()=>{const expected=${JSON.stringify(guideWeaponTypes)};const icons=[...document.querySelectorAll('[data-pickup-icon]')];const types=icons.map(c=>c.dataset.pickupIcon);const catalog=window.SlopCommando.weapons||{};return types.length===expected.length&&new Set(types).size===expected.length&&expected.every(type=>types.includes(type))&&['G','H','W'].every(type=>catalog[type])&&icons.every(c=>c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0))&&new Set(icons.map(c=>c.toDataURL())).size===expected.length;})()`,'fourteen distinct collectible illustrations render in the guide, including grenade, rocket and wave guns');
  await check("[...document.images].every(i=>i.complete&&i.naturalWidth>0)",'brand images loaded');
  await click('#howto');await check("document.querySelector('#dossier').open&&document.querySelectorAll('#mission-list li').length===8",'mission dossier');await click('#close-dossier');
  await click('[data-players="2"]');await click('#start');await sleep(150);
  await check("window.__gameslop.engine.state.players.length===2&&document.querySelector('#title-screen').hidden",'co-op starts');
  await cdp('Input.dispatchKeyEvent',{type:'keyDown',code:'ArrowRight',key:'ArrowRight'});
  await cdp('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyX',key:'x'});
  await cdp('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyD',key:'d'});
  await cdp('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyH',key:'h'});
  await sleep(700);
  await check("window.__gameslop.engine.state.players[0].x>200&&window.__gameslop.engine.state.players[1].x>250",'independent co-op keyboard movement');
  await check("window.__gameslop.engine.state.bullets.some(b=>b.team==='player')",'held fire creates bullets');
  for(const[code,key]of[['ArrowRight','ArrowRight'],['KeyX','x'],['KeyD','d'],['KeyH','h']])await cdp('Input.dispatchKeyEvent',{type:'keyUp',code,key});
  await screenshot('gameplay-desktop');
  await click('#pause');await check("window.__gameslop.engine.state.status==='paused'",'pause button');
  const tick=await evaluate('window.__gameslop.engine.state.tick');await sleep(120);assert.equal(await evaluate('window.__gameslop.engine.state.tick'),tick);console.log('PASS pause freezes simulation');
  await click('#overlay-action');await check("window.__gameslop.engine.state.status==='playing'",'resume button');
  await click('#sound');await check("document.querySelector('#sound').getAttribute('aria-pressed')==='true'",'mute preference');
  await click('#crt');await check("document.querySelector('.scanlines').hidden",'CRT toggle');
  await click('#fullscreen');await sleep(180);await check("!!document.fullscreenElement||document.querySelector('.cabinet').classList.contains('expanded')",'fullscreen enters');
  await check("document.querySelector('.cabinet').contains(document.querySelector('.touch-controls'))",'fullscreen retains mobile controls');
  await click('#fullscreen');await sleep(180);await check("!document.fullscreenElement&&!document.querySelector('.cabinet').classList.contains('expanded')",'fullscreen exits');
  await click('#pause');await click('#restart');await click('[data-players="1"]');
  await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await cdp('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});
  await sleep(100);
  await check("document.documentElement.scrollWidth<=innerWidth",'portrait mobile has no horizontal overflow');
  await check("Math.abs(document.querySelector('#screen').getBoundingClientRect().width/document.querySelector('#screen').getBoundingClientRect().height-16/9)<.02",'portrait mobile preserves landscape playfield');
  await check("(()=>{const list=document.querySelector('.weapon-list'),box=list.getBoundingClientRect(),rows=[...list.children],tops=new Set(rows.map(row=>Math.round(row.getBoundingClientRect().top)));return rows.length===14&&tops.size===7&&list.scrollWidth<=list.clientWidth&&rows.every(row=>{const r=row.getBoundingClientRect(),icon=row.querySelector('canvas').getBoundingClientRect();return r.left>=box.left-1&&r.right<=box.right+1&&r.height>=43&&icon.width>=50&&icon.height>=30;});})()",'portrait mobile guide shows fourteen readable collectible rows in two columns');
  await evaluate("document.querySelector('.guide-weapons').scrollIntoView({block:'center'});");await sleep(80);await screenshot('mobile-guide');await evaluate('window.scrollTo(0,0)');await sleep(40);
  await screenshot('mobile-title');
  await click('#start');await sleep(150);
  await check("(()=>{const el=document.querySelector('.touch-controls'),style=getComputedStyle(el),rect=el.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&rect.width>0&&rect.height>0;})()",'mobile touch controls visible');
  await check("!document.querySelector('.touch-controls [data-action=fire]')",'mobile action buttons omit manual Fire');
  const points=await evaluate("['right','jump'].map(a=>{const r=document.querySelector('[data-action='+a+']').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})");
  const x=await evaluate('window.__gameslop.engine.state.players[0].x');
  await cdp('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points.map((p,i)=>({...p,id:i+1}))});await sleep(500);
  await check(`window.__gameslop.engine.state.players[0].x>${x+50}`,'mobile multi-touch movement');
  await check("window.__gameslop.engine.state.bullets.some(b=>b.team==='player')",'mobile auto-fire while moving and jumping');
  await cdp('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await screenshot('mobile-gameplay');
  await cdp('Emulation.setDeviceMetricsOverride',{width:844,height:390,deviceScaleFactor:1,mobile:true,screenOrientation:{type:'landscapePrimary',angle:90}});await sleep(150);
  await check("document.documentElement.scrollWidth<=innerWidth",'landscape mobile fits viewport');
  await check("(()=>{const s=document.querySelector('#screen').getBoundingClientRect();const controls=[...document.querySelectorAll('[data-action]')].map(e=>e.getBoundingClientRect());return s.top>=0&&s.bottom<=innerHeight&&controls.every(r=>r.top>=0&&r.bottom<=innerHeight);})()",'landscape game and all controls fit onscreen');
  await screenshot('mobile-landscape');
  // Exercise Safari-style lack of element fullscreen support through the supported fallback.
  await evaluate("document.querySelector('.cabinet').requestFullscreen=undefined");await click('#fullscreen');await sleep(100);
  await check("document.querySelector('.cabinet').classList.contains('expanded')",'in-page fullscreen fallback');
  await screenshot('mobile-fullscreen');await click('#fullscreen');
  await check("!(window.__qaErrors||[]).length",'no runtime errors');
  console.log('All browser QA checks passed.');
};
