import test from 'node:test';
import assert from 'node:assert/strict';
import {WEAPONS,chestTotal,defaultSave,syncChests,openChests,CHEST_INTERVAL,upgradeWeapon,unlockedDifficulty,normalizeSave} from '../data.mjs';
import {createRun,chooseBoon,chooseUpgrade,makeWeapon,upgradePreview,completeRun,tick,pathPoint,ultimate,reroll} from '../engine.mjs';
function ready(){const s=defaultSave(100);s.owned=['coin','laser','gas','diamond'];s.specials={owned:{crash:1},equipped:'crash'};const r=createRun(s,0,'easy',42);chooseBoon(r,'damage');chooseUpgrade(r,r.choices[0].id);return {s,r};}
test('idle storage accrues offline in exact 10 minute increments and caps at 32',()=>{const s=defaultSave(0);assert.equal(syncChests(s,CHEST_INTERVAL-1),0);assert.equal(syncChests(s,CHEST_INTERVAL),1);assert.equal(chestTotal(s),5);syncChests(s,CHEST_INTERVAL*100);assert.equal(chestTotal(s),32);assert.equal(s.chestAt,CHEST_INTERVAL*100);const l=openChests(s,99,CHEST_INTERVAL*100,()=>.5);assert.equal(l.count,32);assert.equal(chestTotal(s),0);assert.equal(syncChests(s,CHEST_INTERVAL*100),0);assert.equal(syncChests(s,CHEST_INTERVAL*101),1);});
test('clock rollback never duplicates offline rewards',()=>{const s=defaultSave(60000);syncChests(s,0);assert.equal(chestTotal(s),4);assert.equal(s.chestAt,60000);syncChests(s,660000);assert.equal(chestTotal(s),5);});
test('batch chest claims debit exactly once and award valid shards',()=>{const s=defaultSave(0);const before=s.coins;const l=openChests(s,3,0,()=>.5);assert.equal(l.count,3);assert.equal(s.coins,before+165);assert.equal(chestTotal(s),1);assert.equal(Object.values(l.parts).reduce((a,b)=>a+b),12);assert.equal(openChests(s,32,0,()=>.5).count,1);assert.equal(openChests(s,32,0).count,0);});
test('all weapons have a real initial critical chance, cooldown and critical multiplier',()=>{for(const w of WEAPONS){const a=makeWeapon(w.id);assert.ok(a.crit>0&&a.crit<1);assert.ok(a.damage>0&&a.cooldown>0&&a.mult>1);}});
test('normal, hard and hell unlock per chapter without bypassing prerequisites',()=>{const s=defaultSave();assert.ok(unlockedDifficulty(s,0,'easy'));assert.ok(!unlockedDifficulty(s,0,'hard'));assert.throws(()=>createRun(s,1,'easy'));s.clears['0:easy']=true;assert.ok(unlockedDifficulty(s,0,'hard'));assert.ok(unlockedDifficulty(s,1,'easy'));assert.ok(!unlockedDifficulty(s,1,'hard'));s.clears['0:hard']=true;assert.ok(unlockedDifficulty(s,0,'impossible'));});
test('battle cards only affect the named weapon; 25% crit means percentage points',()=>{const {r}=ready();const w=r.weapons[0],other=r.weapons[1],old=other.damage;r.state='choice';r.pending=1;r.choices=[{id:'coin:crit',weapon:'coin',kind:'crit'}];assert.ok(chooseUpgrade(r,'coin:crit'));assert.ok(Math.abs(w.crit-.35)<1e-8);assert.equal(other.damage,old);assert.ok(!chooseUpgrade(r,'coin:crit'));assert.match(upgradePreview(w,'damage'),/\+50%/);});
test('critical chance caps at 85% and crit hits do multiplied damage',()=>{const {r}=ready();const w=r.weapons[0];w.crit=.8;r.state='choice';r.pending=1;r.choices=[{id:'coin:crit',weapon:'coin',kind:'crit'}];chooseUpgrade(r,'coin:crit');assert.equal(w.crit,.85);});
test('workshop upgrade spends the right resources and cannot overspend',()=>{const s=defaultSave();s.parts.coin=5;assert.ok(upgradeWeapon(s,'coin'));assert.equal(s.levels.coin,2);assert.equal(s.coins,170);assert.ok(!upgradeWeapon(s,'coin'));assert.equal(s.levels.coin,2);assert.ok(!upgradeWeapon(s,'whale'));});
test('gameplay and cooldowns freeze while chest choices or pause are displayed',()=>{const {r}=ready();r.state='choice';const before=JSON.stringify(r);tick(r,.05);assert.equal(JSON.stringify(r),before);r.state='paused';const before2=JSON.stringify(r);tick(r,.05);assert.equal(JSON.stringify(r),before2);});
test('hard and hell start with two and three unique bonuses',()=>{const s=defaultSave();s.clears['0:easy']=s.clears['0:hard']=true;const r=createRun(s,0,'impossible');assert.equal(r.boonsLeft,3);assert.ok(chooseBoon(r,'damage'));assert.ok(!chooseBoon(r,'damage'));chooseBoon(r,'crit');chooseBoon(r,'health');assert.equal(r.health,5);assert.ok(Math.abs(r.weapons[0].crit-.2)<1e-8);assert.equal(r.state,'choice');});
test('victory awards exactly once and unlocks content',()=>{const {s,r}=ready();r.state='won';const first=completeRun(s,r),coins=s.coins;assert.ok(first.first);assert.ok(s.clears['0:easy']);assert.equal(completeRun(s,r),null);assert.equal(s.coins,coins);});
test('rerolls are finite and do not spend idle currency',()=>{const {r}=ready();r.state='choice';r.pending=1;assert.ok(reroll(r));assert.ok(reroll(r));assert.ok(!reroll(r));assert.equal(r.rerolls,0);assert.equal(r.choices.length,3);assert.equal(new Set(r.choices.map(c=>c.id)).size,3);});
test('ultimate refuses during a chest and consumes charge only when fired',()=>{const {r}=ready();r.charge=100;r.state='choice';assert.equal(ultimate(r),false);assert.equal(r.charge,100);r.state='playing';assert.equal(ultimate(r),true);assert.equal(r.charge,0);});
test('rounded snake path is continuous and crosses the vault line',()=>{for(let ch=0;ch<6;ch++){let last=pathPoint(0,ch),crossed=false;for(let d=1;d<2400;d++){const p=pathPoint(d,ch);assert.ok(Math.hypot(p.x-last.x,p.y-last.y)<1.01);assert.ok(Number.isFinite(p.angle));crossed||=p.y>575;last=p;}assert.ok(crossed);}});
test('save roundtrip retains a deterministic resumable battle',()=>{const {r,s}=ready();for(let i=0;i<90;i++)tick(r,.05);s.run=r;const loaded=normalizeSave(JSON.parse(JSON.stringify(s)));assert.ok(loaded.run);tick(r,.05);tick(loaded.run,.05);assert.deepEqual(loaded.run,r);});
test('invalid saves sanitize currency, deck, levels and difficulty',()=>{const s=normalizeSave({version:2,coins:-99,levels:{coin:100},deck:['evil','coin','coin'],difficulty:'nightmare',chests:{rusty:900}});assert.equal(s.coins,0);assert.equal(s.levels.coin,10);assert.equal(chestTotal(s),32);assert.deepEqual(s.deck,['coin']);assert.equal(s.difficulty,'easy');});
test('every weapon deals damage through its own attack behavior',()=>{for(const w of WEAPONS){const {r}=ready();r.weapons=[makeWeapon(w.id)];r.pending=0;r.lastChoice=100;r.headDistance=500;let damage=0;for(let i=0;i<260;i++){tick(r,.05);if(r.state==='choice'){r.pending=0;r.state='playing';}damage=r.weapons[0].totalDamage;}assert.ok(damage>0,`${w.id} did no damage`);}});
test('critical beams multiply damage and bypass armored reduction',()=>{function damage(crit,armor){const {r}=ready();const w=makeWeapon('laser');w.crit=crit;r.weapons=[w];r.segments.forEach(s=>s.armor=armor);tick(r,.05);return w.totalDamage;}const normal=damage(0,false);assert.ok(normal>0);assert.ok(Math.abs(damage(1,false)/normal-2.2)<1e-8);assert.ok(Math.abs(damage(0,true)/normal-.68)<1e-8);assert.equal(damage(1,true),damage(1,false));});
test('expired burning leaves a valid save and contributes ongoing damage',()=>{const {r,s}=ready();r.weapons=[makeWeapon('burn')];tick(r,.05);const w=r.weapons[0],before=w.totalDamage;w.timer=10;r.lastChoice=100;for(let i=0;i<85;i++)tick(r,.05);assert.ok(w.totalDamage>before);assert.ok(r.segments.every(s=>s.burn>=0));s.run=r;assert.ok(normalizeSave(JSON.parse(JSON.stringify(s))).run);});
test('a weaker rug slow cannot cancel the special attack slow',()=>{const {r}=ready();r.weapons.push(makeWeapon('rug'));r.charge=100;ultimate(r);const until=r.slowUntil;tick(r,.05);assert.equal(r.slowAmount,.7);assert.equal(r.slowUntil,until);});
test('damaged or incomplete imported run data is discarded while account progress survives',()=>{const {r,s}=ready();s.coins=800;s.run={...r,bullets:null};const restored=normalizeSave(s);assert.equal(restored.run,null);assert.equal(restored.coins,800);});
test('unattended breaches can lose a siege without resetting or hanging',()=>{const {r}=ready();r.weapons=[];r.lastChoice=10000;r.headDistance=2100;r.health=1;tick(r,.05);assert.equal(r.state,'lost');assert.equal(r.health,0);});

test('campaign special uses the highest-damage collected weapon',()=>{
 const s=defaultSave();s.specials={owned:{crash:1},equipped:'crash'};const r=createRun(s,0,'easy',42);chooseBoon(r,'damage');r.state='playing';r.pending=0;r.weapons=[makeWeapon('coin'),makeWeapon('whale')];for(const w of r.weapons)w.crit=0;
 r.segments=[{id:1,hp:10000,maxHp:10000,x:240,y:200,head:true,markedUntil:0}];r.charge=100;ultimate(r);assert.equal(r.segments[0].hp,10000-210*12);
});
