import {test} from 'node:test';
import assert from 'node:assert/strict';
import {WEAPONS,LEGENDARY,defaultSave,validRun,normalizeSave,weaponUnlocked,unlockWeapon} from '../data.mjs';
import {createRun,chooseBoon,makeWeapon,fire,hit,tick} from '../engine.mjs';
import {updatePositions} from '../snake.mjs';
import {applyCard} from '../upgrades.mjs';
function scene(id,legendary=false){const s=defaultSave(0),r=createRun(s,0,'easy',42);chooseBoon(r,'damage');r.state='playing';r.choices=[];r.pending=0;r.lastChoice=1e6;r.rootUntil=1e6;const w=makeWeapon(id);w.legendary=legendary;w.crit=0;r.weapons=[w];r.segments=r.segments.slice(0,3);r.segments.forEach(s=>{s.hp=s.maxHp=1e7;s.armor=s.regen=s.volatile=false;});updatePositions(r);return {r,w,t:r.segments[0]};}
function advance(r,seconds){for(let i=0;i<Math.ceil(seconds/.05);i++){r.pending=0;r.state='playing';tick(r,.05);}}
test('roster has 24 weapons, six S and seven A grades, and ten unique new types',()=>{assert.equal(WEAPONS.length,24);assert.equal(WEAPONS.filter(w=>w.grade==='S').length,6);assert.equal(WEAPONS.filter(w=>w.grade==='A').length,7);for(const id of ['paper','printer','sniper','halving','slippage','copium','trap','nuke','lambo','flashloan']){assert.equal(WEAPONS.find(w=>w.id===id).type,id);assert.equal(LEGENDARY[id].length,2);}});
test('Paper Hands fires three shots, doubles hurt damage, and gold fires five',()=>{const {r,w,t}=scene('paper');fire(r,w,t);assert.equal(r.bullets.length,3);assert.equal(r.bullets[0].factor,1);r.bullets=[];r.health--;w.legendary=true;fire(r,w,t);assert.equal(r.bullets.length,5);assert.equal(r.bullets[0].factor,2);});
test('Money Printer ramps on one target, resets on a new target, gold retains ramp',()=>{const {r,w,t}=scene('printer');fire(r,w,t);r.time=20;fire(r,w,t);assert.ok(Math.abs(w.timer-.18)<1e-9);fire(r,w,r.segments[1]);assert.equal(w.ramp,0);assert.equal(w.timer,.55);w.legendary=true;r.time=40;fire(r,w,r.segments[1]);const ramp=w.ramp;fire(r,w,t);assert.equal(w.ramp,ramp);});
test('Sniper chooses lowest current health and its guaranteed critical bypasses armor',()=>{const {r,w}=scene('sniper');r.segments[0].hp=5000;r.segments[1].hp=1000;r.segments[1].armor=true;r.segments[2].hp=9000;fire(r,w,r.segments[0]);assert.equal(r.segments[1].hp,1000-120*2.6);assert.equal(r.segments[0].hp,5000);assert.equal(w.crit,0);assert.equal(w.guaranteedCrit,true);});
test('gold Sniper executes below 15% health',()=>{const {r,w,t}=scene('sniper',true);t.hp=1e6;hit(r,t,w);assert.ok(t.hp<=0);});
test('Halving adds a capped max-health strike every fourth cast, gold every second',()=>{for(const [gold,interval] of [[false,4],[true,2]]){const {r,w,t}=scene('halving',gold);for(let i=1;i<interval;i++){const before=t.hp;fire(r,w,t);assert.equal(before-t.hp,88);}const before=t.hp;fire(r,w,t);assert.equal(before-t.hp,88*6);}});
test('Slippage stacks multiply with Oracle and decay, with a raised gold cap',()=>{const {r,w,t}=scene('slippage');for(let i=0;i<8;i++)fire(r,w,t);assert.equal(t.slipStacks,5);t.markedUntil=50;const before=t.hp;hit(r,t,w,100);assert.equal(before-t.hp,175);w.legendary=true;for(let i=0;i<8;i++)fire(r,w,t);assert.equal(t.slipStacks,10);w.timer=20;r.time=6;tick(r,.05);assert.equal(t.slipStacks,9);});
test('Copium contact restores one shield per 45 seconds, gold doubles charge, overlaps count once',()=>{for(const gold of [false,true]){const {r,w,t}=scene('copium',gold);r.health=3;w.shieldCharge=44.96;fire(r,w,t);fire(r,w,t);w.timer=20;tick(r,.05);assert.equal(r.health,4);assert.ok(Math.abs(w.shieldCharge-(gold?.06:.01))<1e-8);r.health=r.maxHealth;w.shieldCharge=44.96;tick(r,.05);assert.equal(r.health,r.maxHealth);}});
test('Copium gains no charge without section contact',()=>{const {r,w,t}=scene('copium');fire(r,w,t);r.effects.forEach(e=>{e.x=0;e.y=0;});w.timer=20;tick(r,.05);assert.equal(w.shieldCharge,0);});
test('Bear Trap arms on the path, crossing detonates and roots for two seconds',()=>{const {r,w,t}=scene('trap');r.rootUntil=0;fire(r,w,t);const trap=r.effects.find(e=>e.type==='trap');assert.ok(trap.armed);assert.ok(trap.distance>t.distance);r.headDistance+=36;updatePositions(r);w.timer=20;tick(r,.05);assert.ok(r.rootUntil>=r.time+1.99);assert.ok(!r.effects.some(e=>e.type==='trap'&&e.armed));const distance=r.headDistance;tick(r,.05);assert.equal(r.headDistance,distance);});
test('gold Bear Trap chains one secondary trap only after detonation',()=>{const {r,w,t}=scene('trap',true);fire(r,w,t);assert.equal(r.effects.filter(e=>e.type==='trap').length,1);r.headDistance+=36;updatePositions(r);w.timer=20;tick(r,.05);assert.ok(r.castId>=r.effects[0]?.id||r.rootUntil>r.time);assert.ok(r.rootUntil>r.time);});
test('Nonce Nuke hits all visible sections with falloff, gold removes falloff',()=>{for(const gold of [false,true]){const {r,w,t}=scene('nuke',gold);fire(r,w,t);assert.equal(1e7-t.hp,150);const tailDamage=1e7-r.segments[2].hp;assert.ok(tailDamage>0);if(gold)assert.equal(tailDamage,150);else assert.ok(tailDamage<150);}});
test('Lambo follows the body path and gold strikes again on its return pass',()=>{for(const gold of [false,true]){const {r,w,t}=scene('lambo',gold);fire(r,w,t);w.timer=20;advance(r,2);const damage=1e7-r.segments[1].hp;assert.equal(damage,gold?84:42);assert.ok(w.totalDamage>=damage);}});
test('Lambo travel increases with permanent weapon level',()=>{const {r,w,t}=scene('lambo');fire(r,w,t);const low=r.effects[0].range;r.effects=[];w.level=50;fire(r,w,t);assert.ok(r.effects[0].range>low);});
test('Flash Loan suppresses firing during live debt even with a fast cooldown',()=>{const {r,w,t}=scene('flashloan');w.cooldown=.1;fire(r,w,t);const before=t.hp;advance(r,2);assert.equal(t.hp,before);assert.ok(w.debtUntil>r.time);advance(r,.6);assert.ok(t.hp<before);});
test('Flash Loan kill forgiveness skips repayment and gold refunds the remaining cooldown',()=>{for(const gold of [false,true]){const {r,w,t}=scene('flashloan',gold);fire(r,w,t);w.timer=3.2;t.hp=0;tick(r,.05);if(gold)assert.ok(w.totalDamage>340);else {assert.ok(w.timer<.71);assert.equal(w.debtUntil,0);}}});
for(const id of ['paper','printer','sniper','halving','slippage','copium','trap','nuke','lambo','flashloan'])test(`${id} gold evolution and active state survive save round trip`,()=>{const {r,w,t}=scene(id);applyCard(w,{kind:'legendary',rarity:'gold'});fire(r,w,t);const s=defaultSave(0);s.run=r;assert.ok(validRun(r));const restored=normalizeSave(JSON.parse(JSON.stringify(s)),0);assert.ok(restored.run);assert.equal(restored.run.weapons[0].legendary,true);});
test('new weapon runtime state rejects invalid debt, ramp, stacks and trap identities',()=>{for(const mutate of [({w})=>w.debtUntil=NaN,({w})=>w.ramp=-1,({w})=>w.shieldCharge=46,({r})=>r.segments[0].slipStacks=11,({r})=>r.effects[0].id=-1]){const env=scene('trap');fire(env.r,env.w,env.t);mutate(env);assert.equal(validRun(env.r),false);}});
test('acquisition grants C/B on Easy and A on Hard; S costs 22 blueprints after discovery',()=>{const s=defaultSave(0),by=id=>WEAPONS.find(w=>w.id===id);assert.equal(weaponUnlocked(s,by('paper')),false);s.clears['6:easy']=true;assert.ok(weaponUnlocked(s,by('paper')));s.clears['37:easy']=true;assert.equal(weaponUnlocked(s,by('sniper')),false);s.clears['37:hard']=true;assert.ok(weaponUnlocked(s,by('sniper')));s.blueprints=22;s.furthest.easy=79;assert.equal(unlockWeapon(s,'flashloan'),false);s.furthest.easy=80;assert.ok(unlockWeapon(s,'flashloan'));assert.equal(s.blueprints,0);assert.ok(weaponUnlocked(s,by('flashloan')));});
