import {test} from 'node:test';
import assert from 'node:assert/strict';
import {VERSION,LEVELS,ACT_ANCHORS,WEAPONS,DIFFICULTIES,defaultSave,normalizeSave,validRun,migratedLevel,migratedChapter,encounterHealth,rawPool,upgradeCost,upgradeWeapon,rankUp,rankCost,upgradeFoundry,refine,openChests,syncChests,chestTotal,CHEST_INTERVAL,arsenalSlots,highestUnlocked,BASE_POOL} from '../data.mjs';
import {createRun,chooseBoon,spawnWave,makeWeapon} from './legacy-engine.mjs';
import {AutoSync} from '../autosync.mjs';
const openSave=()=>{const s=defaultSave(0);for(let i=0;i<100;i++)for(const d of DIFFICULTIES)s.clears[`${i}:${d.id}`]=true;return normalizeSave(s,0);};
function active(){const s=openSave();const r=createRun(s,99,'impossible',42);while(r.state==='boon')chooseBoon(r,r.boonOptions[0]);return r;}
test('100 generated levels use the anchors and exact encounter health after section grouping',()=>{assert.equal(LEVELS.length,100);assert.equal(new Set(LEVELS.map(l=>l.act)).size,10);const base=BASE_POOL;for(let i=0;i<100;i++){const s=openSave(),r=createRun(s,i,'easy',42);let total=0;for(let w=1;w<=LEVELS[i].waves;w++){spawnWave(r);assert.ok(r.segments.reduce((n,s)=>n+s.pieces,0)<=64);total+=r.segments.reduce((n,s)=>n+s.maxHp,0);}assert.ok(Math.abs(total/base/encounterHealth(i+1)-1)<.01);}});
test('v1 migration keeps coins, parts, scores, owned weapons and all matching clears',()=>{const old={version:1,coins:123456,levels:Object.fromEntries(WEAPONS.map(w=>[w.id,10])),shards:Object.fromEntries(WEAPONS.map(w=>[w.id,93])),clears:{'14:normal':true,'14:hard':true,'14:hell':true},best:{'14:hell':999999},chests:20,chestAt:0,selected:14,difficulty:'hell'};const s=normalizeSave(old,0);assert.equal(migratedChapter(14),20);assert.equal(s.version,2);assert.equal(s.coins,old.coins);assert.equal(s.chests.rusty,20);assert.equal(s.cores,WEAPONS.length*8);assert.equal(s.best['20:impossible'],999999);assert.deepEqual(s.furthest,{easy:21,hard:21,impossible:21});for(let i=0;i<=20;i++)for(const d of DIFFICULTIES)assert.ok(s.clears[`${i}:${d.id}`]);for(const w of WEAPONS){assert.equal(s.levels[w.id],7);assert.equal(s.ranks[w.id],2);assert.equal(s.parts[w.id],114);assert.ok(1.135**(s.levels[w.id]-1)>=2.08);}assert.equal(s.difficulty,'impossible');});
test('migration never loses weapon damage at any legacy level',()=>{for(let l=1;l<=10;l++){assert.ok(1.135**(migratedLevel(l)-1)+1e-9>=1+.12*(l-1));if(l>1)assert.ok(1.135**(migratedLevel(l)-2)<1+.12*(l-1));}});
test('legacy active campaign and tournament migrate without discarding battle builds',()=>{const s=defaultSave(0),r=active();r.version=1;r.chapter=14;r.difficulty='hell';r.baseLevels=Object.fromEntries(WEAPONS.map(w=>[w.id,10]));const damage=r.weapons[0].damage;r.state='paused';s.version=1;s.shards=s.parts;s.chests=4;s.run=r;s.tournamentRun={...structuredClone(r),mode:'tournament',revivesUsed:2};const out=normalizeSave(s,0);assert.ok(out.run);assert.ok(out.tournamentRun);assert.equal(out.run.weapons[0].damage,damage);assert.equal(out.run.chapter,20);assert.equal(out.tournamentRun.revivesUsed,2);});
for(const [name,mutate] of [
 ['level 100 accepted',r=>r.chapter=99],['six waves accepted',r=>r.wave=6],['ten shields accepted',r=>r.health=r.maxHealth=10],['eight weapons accepted',r=>{r.slots=8;r.weapons=WEAPONS.slice(0,8).map(w=>makeWeapon(w.id));}],['weapon level 50 accepted',r=>r.baseLevels.coin=50]
])test(name,()=>{const r=active();mutate(r);assert.equal(validRun(r),true);});
for(const [name,mutate] of [
 ['level 101 rejected',r=>r.chapter=100],['negative chapter rejected',r=>r.chapter=-1],['fractional chapter rejected',r=>r.chapter=.5],['seven waves rejected',r=>r.wave=7],['eleven shields rejected',r=>r.health=r.maxHealth=11],['health above maximum rejected',r=>{r.maxHealth=5;r.health=6;}],['nine weapons rejected',r=>{r.slots=8;r.weapons=WEAPONS.slice(0,9).map(w=>makeWeapon(w.id));}],['seven weapons in six slots rejected',r=>{r.slots=6;r.weapons=WEAPONS.slice(0,7).map(w=>makeWeapon(w.id));}],['weapon level 51 rejected',r=>r.baseLevels.coin=51],['fractional weapon level rejected',r=>r.baseLevels.coin=1.5],['invalid difficulty rejected',r=>r.difficulty='normal']
])test(name,()=>{const r=active();mutate(r);assert.equal(validRun(r),false);});
test('grade costs, rank caps and Foundry spend the right currencies',()=>{const s=openSave();s.coins=1e7;s.parts.coin=1e5;s.cores=1000;assert.deepEqual(upgradeCost(1,'C'),{coins:70,parts:5});for(let i=1;i<10;i++)assert.ok(upgradeWeapon(s,'coin'));assert.equal(upgradeWeapon(s,'coin'),false);assert.equal(rankCost(1),8);assert.ok(rankUp(s,'coin'));assert.equal(s.cores,992);assert.ok(upgradeWeapon(s,'coin'));assert.ok(upgradeFoundry(s,'vault'));assert.equal(s.foundry.vault,1);});
test('Refinery converts 3 to 1 and rejects invalid or unfunded transfers',()=>{const s=openSave();s.parts.coin=9;assert.ok(refine(s,'coin','gas',3));assert.equal(s.parts.coin,0);assert.equal(s.parts.gas,3);assert.equal(refine(s,'coin','gas'),false);assert.equal(refine(s,'gas','gas'),false);assert.equal(refine(s,'gas','coin',-1),false);});
test('tiered chests share one cap and award total parts across distinct weapons',()=>{const s=openSave();s.chests={rusty:0,reinforced:0,armored:0,vault:1};const loot=openChests(s,1,0,()=>0);assert.equal(loot.coins,1200);assert.equal(loot.cores,6);assert.equal(loot.blueprints,3);assert.equal(Object.keys(loot.parts).length,4);assert.equal(Object.values(loot.parts).reduce((a,b)=>a+b,0),90);syncChests(s,100*CHEST_INTERVAL,()=>0);assert.equal(chestTotal(s),32);assert.equal(s.chests.vault,32);});
test('automatic picker follows highest unlocked until player selects a farming level',()=>{const s=openSave();assert.equal(arsenalSlots(s),8);assert.equal(highestUnlocked(s),99);s.selected=29;s.selectedManual=true;assert.equal(normalizeSave(s,0).selected,29);s.selectedManual=false;assert.equal(normalizeSave(s,0).selected,99);});
test('cloud snapshot with lower save version cannot overwrite a newer local schema',async()=>{const local=defaultSave(0);local.updatedAt=10;let restored=false,written;const sync=new AutoSync({storage:{load:async()=>({save:{version:1,updatedAt:999}}),save:async s=>written=s},read:()=>local,restore:()=>restored=true});await sync.start();sync.stop();assert.equal(restored,false);assert.equal(written.version,2);});
