import test from 'node:test';import assert from 'node:assert/strict';
import {WEAPONS,CHAPTERS,UPGRADE_RARITIES,defaultSave,normalizeSave,validRun,weaponUnlocked} from '../data.mjs';
import {createRun,chooseBoon,chooseUpgrade,makeWeapon,offerChoice,tick,completeRun} from '../engine.mjs';
import {rollRarity,drawCards,applyCard,preview} from '../upgrades.mjs';
function account(){const s=defaultSave();for(let i=0;i<CHAPTERS.length;i++)s.clears[i+':normal']=s.clears[i+':hard']=true;return s;}
function playing(id='coin'){const s=account(),r=createRun(s,0,'normal',731);chooseBoon(r,'damage');r.weapons=[makeWeapon(id)];r.pending=0;r.choices=[];r.state='playing';r.lastChoice=1000;return {s,r,w:r.weapons[0]};}
test('15 chapters get strictly tougher and all new weapons unlock only after the named clear',()=>{assert.equal(CHAPTERS.length,15);assert.equal(WEAPONS.length,14);for(let i=1;i<CHAPTERS.length;i++){assert.ok(CHAPTERS[i].hp>CHAPTERS[i-1].hp);assert.ok(CHAPTERS[i].speed>CHAPTERS[i-1].speed);}for(const w of WEAPONS.filter(w=>w.unlock)){const s=defaultSave();assert.equal(weaponUnlocked(s,w),false);s.clears[(w.unlock-1)+':normal']=true;assert.equal(weaponUnlocked(s,w),true);}});
test('rarity rolls match 60/28/10/2 and actual choices do not dilute Gold as the arsenal grows',()=>{const counts={green:0,blue:0,red:0,gold:0},rng={seed:374982};for(let i=0;i<120000;i++)counts[rollRarity(rng)]++;for(const t of UPGRADE_RARITIES)assert.ok(Math.abs(counts[t.id]/120000-t.weight/100)<.006,JSON.stringify(counts));
 for(const ids of [['coin'],WEAPONS.slice(0,6).map(w=>w.id)]){const {r}=playing();r.weapons=ids.map(id=>makeWeapon(id));r.deck=WEAPONS.map(w=>w.id);let gold=0,n=0;for(let j=0;j<10000;j++){const cards=drawCards(r);assert.equal(cards.length,3);assert.equal(new Set(cards.map(c=>c.id)).size,3);for(const c of cards){gold+=c.rarity==='gold';n++;}}assert.ok(Math.abs(gold/n-.02)<.005,gold/n);}});
test('stronger tiers strictly increase stat benefits and preview matches real gain',()=>{for(const tier of UPGRADE_RARITIES){const w=makeWeapon('coin'),old=w.damage;applyCard(w,{kind:'damage',rarity:tier.id});assert.equal(w.damage,old*(1+tier.damage));const crit=makeWeapon('coin');applyCard(crit,{kind:'crit',rarity:tier.id});assert.ok(Math.abs(crit.crit-(.1+tier.crit))<1e-9);assert.match(preview(makeWeapon('coin'),'damage',tier.id),new RegExp(String(Math.round(old*(1+tier.damage)))));}});
test('a new chapter and retry collect weapons from scratch; workshop and unlocks persist',()=>{const s=account();s.levels.coin=5;const r=createRun(s,0,'normal',42);chooseBoon(r,'damage');chooseUpgrade(r,r.choices[0].id);r.weapons[0].damage*=20;r.weapons[0].legendary=true;r.state='won';completeRun(s,r);for(const ch of [0,1]){const next=createRun(s,ch,'normal',53);chooseBoon(next,'damage');assert.deepEqual(next.weapons.map(w=>w.id),['coin']);assert.equal(next.weapons[0].upgrades,0);assert.equal(next.weapons[0].legendary,false);assert.equal(next.weapons[0].damage,makeWeapon('coin',5,['damage']).damage);assert.equal(next.deck.length,14);}});
test('no unavailable weapon enters a run and no seventh weapon is offered',()=>{const s=defaultSave();s.deck=WEAPONS.map(w=>w.id);const r=createRun(s);assert.deepEqual(r.deck,['coin','laser','gas','diamond']);chooseBoon(r,'damage');assert.ok(r.choices.every(c=>c.kind==='unlock'&&c.rarity==='green'));r.deck=WEAPONS.map(w=>w.id);r.weapons=WEAPONS.slice(0,6).map(w=>makeWeapon(w.id));for(let i=0;i<100;i++)assert.ok(drawCards(r).every(c=>c.kind!=='unlock'));});
test('legendary evolutions require three upgrades, are Gold only, and cannot be chosen twice',()=>{const {r,w}=playing();r.deck=['coin'];for(let i=0;i<100;i++)assert.ok(drawCards(r).every(c=>c.kind!=='legendary'));w.upgrades=3;let seen=false;for(let i=0;i<500;i++){const c=drawCards(r).find(c=>c.kind==='legendary');if(c){assert.equal(c.rarity,'gold');seen=true;break;}}assert.ok(seen);applyCard(w,{kind:'legendary',rarity:'gold'});assert.equal(applyCard(w,{kind:'legendary',rarity:'gold'}),false);for(let i=0;i<100;i++)assert.ok(drawCards(r).every(c=>c.kind!=='legendary'));});
test('all fourteen legendary weapon builds produce damage and keep a resumable save',()=>{for(const def of WEAPONS){const {s,r,w}=playing(def.id);w.legendary=true;for(let n=0;n<180;n++){tick(r,.05);if(r.state==='choice'){r.pending=0;r.state='playing';}}assert.ok(w.totalDamage>0,def.id);s.run=r;assert.ok(normalizeSave(JSON.parse(JSON.stringify(s))).run,def.id);}});
test('orbital percentage damage is capped and Oracle marks amplify another weapon',()=>{const {r,w}=playing('satellite');r.segments.forEach(s=>{s.hp=s.maxHp=1e9;s.armor=false;});w.crit=0;tick(r,.05);assert.ok(w.totalDamage>0);assert.ok(w.totalDamage<=r.segments.length*w.damage*5);
 function laser(marked){const {r,w}=playing('laser');w.crit=0;r.segments.forEach(s=>{s.markedUntil=marked?100:0;s.armor=false;});tick(r,.05);return w.totalDamage;}assert.ok(Math.abs(laser(true)/laser(false)-1.25)<1e-9);});
test('homing bots retarget, forks split, dragon trails persist and vortex ticks after casting',()=>{for(const id of ['swarm','fork','dragon','vortex']){const {r,w}=playing(id);tick(r,.05);if(id==='swarm'){const shot=r.bullets[0];r.segments.find(s=>s.id===shot.targetId).hp=0;tick(r,.05);assert.ok(r.segments.some(s=>s.id===shot.targetId&&s.hp>0));}if(id==='vortex'){const before=w.totalDamage;w.timer=10;for(let i=0;i<15;i++)tick(r,.05);assert.ok(w.totalDamage>before);}if(id==='fork'){const shot=r.bullets[0],target=r.segments[4];shot.x=target.x;shot.y=target.y;shot.vx=shot.vy=0;tick(r,.01);assert.ok(r.bullets.some(b=>b.type==='fragment'));}if(id==='dragon'){for(let i=0;i<10;i++)tick(r,.05);assert.ok(r.effects.some(e=>e.type==='hazard'&&e.weapon==='dragon'));}}});
test('choice time, effects and projectiles freeze exactly; resume preserves rolled cards',()=>{const {s,r}=playing('dragon');for(let i=0;i<10;i++)tick(r,.05);r.pending=1;offerChoice(r);const before=JSON.stringify(r);for(let i=0;i<100;i++)tick(r,.05);assert.equal(JSON.stringify(r),before);s.run=r;const loaded=normalizeSave(JSON.parse(JSON.stringify(s)));assert.deepEqual(loaded.run,r);});
test('old saves gain new weapon fields without losing active progress or old card behavior',()=>{const {s,r}=playing();r.weapons[0].upgrades=8;s.run=r;for(const w of WEAPONS.slice(8)){delete r.baseLevels[w.id];delete s.levels[w.id];delete s.shards[w.id];}delete r.weapons[0].legendary;r.choices=[{id:'coin:crit',weapon:'coin',kind:'crit',rarity:'rare',title:'Critical mass',description:'Old card'}];r.state='choice';r.pending=1;const migrated=normalizeSave(s);assert.ok(migrated.run);assert.equal(migrated.run.weapons[0].upgrades,8);assert.equal(migrated.levels.dragon,1);assert.ok(migrated.run.choices[0].legacy);chooseUpgrade(migrated.run,'coin:crit');assert.ok(Math.abs(migrated.run.weapons[0].crit-.35)<1e-9);});
test('Gold Oracle executes marked low-health segments and Gold forks produce a second generation',()=>{
 const {r,w}=playing('laser');w.damage=1;w.crit=0;const oracle=makeWeapon('oracle');oracle.legendary=true;oracle.timer=10;r.weapons.push(oracle);r.segments.forEach(s=>{s.maxHp=100;s.hp=9;s.markedUntil=100;});tick(r,.01);assert.ok(r.kills>0);
 const {r:fr,w:fw}=playing('fork');fw.legendary=true;tick(fr,.01);let shot=fr.bullets[0],target=fr.segments[4];Object.assign(shot,{x:target.x,y:target.y,vx:0,vy:0});tick(fr,.01);shot=fr.bullets.find(b=>b.generation===1);assert.ok(shot);target=fr.segments.find(s=>s.id===shot.targetId);Object.assign(shot,{x:target.x,y:target.y,age:.1});tick(fr,.01);assert.ok(fr.bullets.some(b=>b.generation===2));
});
test('invalid hazard damage cannot poison a resumed simulation',()=>{const {s,r}=playing('vortex');tick(r,.05);const hazard=r.effects.find(e=>e.type==='hazard');assert.ok(hazard);hazard.amount='broken';s.run=r;assert.equal(normalizeSave(s).run,null);});
