import {WEAPONS,FOUNDRY,CHESTS,LEGENDARY,weaponUnlocked,upgradeCost,rankCost,foundryCost,arsenalSlots,chestTotal} from './data.mjs';
import {makeWeapon} from './engine.mjs';
import {compactNumber as fmt,effectiveDps} from './presentation.mjs';
const range=a=>a[0]===a[1]?String(a[0]):a.join(' to ');
export function armoryView(save,icon){
 return `<div class="bottom-strip"><div class="strip-copy"><b>${WEAPONS.filter(w=>weaponUnlocked(save,w)).length} / 24 weapons unlocked · ${arsenalSlots(save)} battle slots</b><p>Each run starts with Mint Condition. Find your other weapons in battle. Slots 7 and 8 unlock after Easy levels 30 and 65. Permanent investment makes a weapon more likely to appear.</p></div><button class="secondary" data-action="refinery">Refinery · 3:1</button></div><div class="weapon-grid">${WEAPONS.map(w=>{
 const unlocked=weaponUnlocked(save,w),l=save.levels[w.id],rank=save.ranks[w.id],cost=upgradeCost(l,w.grade),stats=makeWeapon(w.id,l,[],rank,save.foundry),cap=rank*10,discovered=save.furthest.easy>=w.discovery;
 return `<article data-weapon="${w.id}" class="weapon-card ${unlocked?'':'locked'}"><div class="weapon-top">${icon(w.id)}<span>GRADE ${w.grade}<br>RANK ${rank} / 5<br>LV ${l} / 50</span></div><span class="eyebrow">${w.class} · ${w.tag}</span><h3>${w.name}</h3><p>${w.description}</p><div class="weapon-stats"><span>HIT DAMAGE<b title="${stats.damage}">${fmt(stats.damage)}</b></span><span>COOLDOWN<b>${stats.cooldown.toFixed(2)}s</b></span><span>CRIT CHANCE<b>${stats.guaranteedCrit?'Always':Math.round(stats.crit*100)+'%'}</b></span><span>CRIT DAMAGE<b>${stats.mult.toFixed(2)}×</b></span><span>NOMINAL DPS<b title="Single target, before conditional effects and area overlap">${fmt(effectiveDps(stats))}</b></span><span>PARTS OWNED<b>${fmt(save.parts[w.id])}</b></span></div><div class="weapon-unlock">${unlocked?w.id==='coin'?'STARTER · EVERY RUN':'UNLOCKED · FIND IN BATTLE':w.grade==='S'?`${discovered?'DISCOVERED':'DISCOVER AT EASY '+w.discovery} · ${Math.min(22,save.blueprints)} / 22 BLUEPRINTS`:`CLEAR ${w.grade==='A'?'HARD':'EASY'} LEVEL ${w.discovery}`}</div><details class="legendary-preview"><summary>Gold evolution</summary><b>${LEGENDARY[w.id][0]}</b><p>${LEGENDARY[w.id][1]}</p></details>${!unlocked&&w.grade==='S'?`<button class="primary" data-unlock="${w.id}" ${discovered&&save.blueprints>=22?'':'disabled'}>Unlock · 22 blueprints</button>`:l>=cap&&rank<5?`<button class="primary" data-rank="${w.id}" ${unlocked&&save.cores>=rankCost(rank)?'':'disabled'}>Rank up · ${rankCost(rank)} cores</button><div class="cost">+12% damage · level cap ${cap+10}</div>`:`<button class="primary" data-upgrade="${w.id}" ${!unlocked||l>=50||save.coins<cost.coins||save.parts[w.id]<cost.parts?'disabled':''}>${l>=50?'Fully upgraded':'Upgrade · '+fmt(cost.coins)+' coins'}</button><div class="cost">${l<50?fmt(cost.parts)+' parts needed · rank cap '+cap:'Masterwork weapon'}</div>`}</article>`;
 }).join('')}</div>`;
}
export function foundryView(save){return `<p class="info-card">Permanent upgrades affect every weapon, including weapons you find later in a run. Purchases apply to your next run.</p><div class="guide-grid">${Object.entries(FOUNDRY).map(([id,t])=>{const level=save.foundry[id],cost=foundryCost(level+1);const current=id==='ordnance'?(1.08**level).toFixed(2)+'× damage':id==='precision'?'+'+level+' crit points, +'+(.02*level).toFixed(2)+'× crit damage':id==='overclock'?(.55*level).toFixed(2)+'% shorter cooldown':'+'+Math.floor(level/8)+' shields';return `<article class="info-card foundry-card"><span class="eyebrow">LEVEL ${level} / ${t.max}</span><h2>${t.name}</h2><p>${t.description}</p><strong>${current}</strong><progress value="${level}" max="${t.max}" aria-label="${t.name} level ${level} of ${t.max}"></progress><button class="primary" data-foundry="${id}" ${level>=t.max||save.coins<cost?'disabled':''}>${level>=t.max?'Complete': 'Upgrade · '+fmt(cost)+' coins'}</button></article>`;}).join('')}</div>`;}
export function vaultView(save,icon){const total=chestTotal(save);return `<div class="bottom-strip"><div class="strip-copy"><b id="vault-count">${total} / 32 chests</b><p id="vault-timer"></p></div><button class="primary" data-open="32" ${total?'':'disabled'}>Open all · ${total}</button></div><div class="guide-grid">${Object.entries(CHESTS).map(([id,c])=>`<article class="info-card chest-tier ${id}">${icon('chest')}<span class="eyebrow">${save.chests[id]} STORED</span><h2>${id[0].toUpperCase()+id.slice(1)}</h2><p>${range(c.coins)} coins<br>${range(c.parts)} parts across up to ${c.weapons} weapons<br>${range(c.cores)} cores<br>${Math.round(c.chance*100)}% chance: ${range(c.blueprints)} blueprints</p><button class="secondary" data-open="1" data-tier="${id}" ${save.chests[id]?'':'disabled'}>Open one</button><button class="primary" data-open="32" data-tier="${id}" ${save.chests[id]?'':'disabled'}>Open ${id} batch</button></article>`).join('')}</div><p class="info-card">One idle chest arrives every ten minutes, up to 32 total. Better tiers become more common as you progress, with shifts after Easy levels 20, 40 and 70. Every tenth Easy first clear grants a Vault chest and 3 blueprints. Parts are spread across unlocked weapons.</p>`;}
export function refineryView(save){return `<span class="eyebrow">TURN SPARES INTO PROGRESS</span><h2 id="modal-title">The Refinery.</h2><p>Trade 3 spare parts for 1 part of any unlocked weapon. Coins, cores and blueprints are unchanged.</p><label class="setting">From<select id="refine-from">${WEAPONS.filter(w=>save.parts[w.id]>=3).map(w=>`<option value="${w.id}">${w.name} · ${save.parts[w.id]} parts</option>`).join('')}</select></label><label class="setting">To<select id="refine-to">${WEAPONS.filter(w=>weaponUnlocked(save,w)).map(w=>`<option value="${w.id}">${w.name}</option>`).join('')}</select></label><label class="setting">Parts to receive<input id="refine-count" type="number" value="1" min="1" step="1" inputmode="numeric"></label><p id="refine-preview" role="status"></p><div class="modal-actions"><button class="secondary" data-action="close">Back</button><button class="primary" id="refine-submit" data-action="refine">Exchange parts</button></div>`;}
